include themes/GruvBox_DarkHard.conf

font_size 18.0

macos_option_as_alt yes

# https://github.com/kovidgoyal/kitty/issues/371
mouse_map left click ungrabbed mouse_handle_click prompt
mouse_map cmd+left click ungrabbed mouse_handle_click link

map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
# no ctrl+w because I use it in vim
