return {
    'nvim-treesitter/nvim-treesitter',
    lazy = false,
    build = ':TSUpdate',
    config = function()
        require('nvim-treesitter').setup({
            ensure_installed = {
                'angular',
                'bash',
                'c',
                'cmake',
                'cpp',
                'css',
                'c_sharp',
                'go',
                'git_config',
                'gitignore',
                'graphql',
                'haskell',
                'html',
                'java',
                'javadoc',
                'javascript',
                'json',
                'jsx',
                'kitty',
                'lua',
                'make',
                'markdown',
                'meson',
                'prisma',
                'python',
                'rust',
                'sql',
                'toml',
                'tsx',
                'typescript',
                'vim',
                'xml',
                'yaml',
                'zsh',
            },
            hightlight = { enable = true },
            indent = { enable = true },
        })
    end,
}
